### ISSUE TITLE
Spotify notification

### ISSUE THREAD

**Issue by omgpercy** [rosenpin/AlwaysOnDisplayAmoled#1157]
Samsung J7 Prime
6.0.1
Latest beta Version of Always On

It doesn't display the song. It just shows the player then the word "Fall" on top of it.

**Comment by Aaahh** [comment]
Spotify notification doesnt always show up, play and pause keys sometimes don't show up, or show up after closing Spotify
Or show playing when it's paused
This isn't really Spotify exclusive, read the notifications on screen lock not just intercept new ones while locked

**Comment by rosenpin** [comment]
Should be fixed
