### ISSUE TITLE
Home button doesn't work on Samsung devices.

### ISSUE THREAD

**Issue by rosenpin** [rosenpin/AlwaysOnDisplayAmoled#12]
Home button should turn on the display and dismiss the app.

**Comment by jdrescher2006** [comment]
This is funny. I have a Samsung Galaxy S5 and thought this was a feature.
I like it that only the power button is able to turn on the display, the home button might be accidently pushed.
If you get this "bug" fixed, it would be nice to have this as an option (home button can turn on display).

**Comment by rosenpin** [comment]
Thanks for the feedback.
If I ever get around to fixing this bug, I'll make it optional.

From what I read, in order to get home button press event the user has to allow accessibility access to the app.
So it will be optional.

**Comment by davidhedlund** [comment]
@rosenpin Why is this issue closed?

**Comment by davidhedlund** [comment]
[mylabel:declined](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Adeclined%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by rosenpin** [comment]
It works in the latest beta

**Comment by davidhedlund** [comment]
[mylabel:re-evaluate](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Are-evaluate%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
@rosenpin Thanks.

**Comment by rosenpin** [comment]
Please note that you have to manually enable it by opening the app, click the gestures section, and under "Samsung" enable "Home button to unlock"

**Comment by davidhedlund** [comment]
@rosenpin Can you show that tip once installed on Samsung devices?
