### ISSUE TITLE
Home Button Unlock not working when Greenify is enabled

### ISSUE THREAD

**Issue by JoshuaDR** [rosenpin/AlwaysOnDisplayAmoled#1206]
As simple as the title says, the option "Home Button Unlocks" only works if I disable the "Greenify integration" option. I notice this because usually I use my home button to exit the always-on screen. For you to know I am using the Samsung J7 2016.

**Comment by mattelacchiato** [comment]
For me, Home Button unlock does not work even without greenify. Note 4

**Comment by rosenpin** [comment]
There's now an option to use the simulated home button (in the latest beta), works 100%, might not be as easy to use though
