### ISSUE TITLE
Cannot complete permission setup on SM-T700

### ISSUE THREAD

**Issue by seattleandrew** [rosenpin/AlwaysOnDisplayAmoled#1344]
I have a Samsung Tab S 7.0" (SM-T700) on Android 6.0, when I get to the stage "Modify System Settings" when I click on the "Allow Now" button it takes me to the WiFi section of the Settings menu. I have gone into the settings and allowed Always On AMOLED to be a device administrator and I allowed Notification Access but when I try hitting the checkmark on the final stage, it says "Please allow all permissions"

What else do I need to do? This seems like a bug.

**Comment by rosenpin** [comment]
It's a bug in Samsung's operating system.
They changed the "Modify system settings" screen for some reason.
Please open your settings app and search "Modify system settings", you need to grant Always On AMOLED this permission so it can control the screen brightness.
