### ISSUE TITLE
Turns on and off

### ISSUE THREAD

**Issue by areebbeigh** [rosenpin/AlwaysOnDisplayAmoled#1394]
The app display goes on and off i.e for about a minute I have the time screen enabled and the next I'm on the lock screen. 

Device: Xiaomi Redmi 2
Android version: 5.1
Method to turn off the display: Double tap (nothing else)
Pocket mode: On
SU permissions: Yes
Greenify Integration: On

**Comment by rosenpin** [comment]
What version of the app are you using?

**Comment by areebbeigh** [comment]
v0.9.6 beta build: 241

**Comment by areebbeigh** [comment]
OK so I took a video (GIF)

![videotogif_2016 12 13_19 05 57](https://cloud.githubusercontent.com/assets/15276828/21142306/8792cadc-c167-11e6-8f89-48cc0e00fea4.gif)

**Comment by rosenpin** [comment]
Is the issue still present?

**Comment by areebbeigh** [comment]
Nope, seems to be working fine now.

**Comment by rosenpin** [comment]
Great! Thanks for your input :+1:
