### ISSUE TITLE
Auto-brightness will be deactivated after using the AoD

### ISSUE THREAD

**Issue by ErikSteiner** [rosenpin/AlwaysOnDisplayAmoled#1401]
I don't know if this is a missing feature or a bug. I set the brightness in the App to 10% and the display brightness of my phone to Auto. When unlocking my phone while the AoD is active, my display brightness will be set to manual.

**Comment by rosenpin** [comment]
Sorry for the late response.
This is very odd, if it's still relevant, could you let me know what device/android version are you using?
Can you try uninstalling then reinstalling the app and let me know if the problem persists?
