### ISSUE TITLE
Notification Touch Activates Screen

### ISSUE THREAD

**Issue by lorenhpearson** [rosenpin/AlwaysOnDisplayAmoled#1435]
Tomer,

I still love your software after using it for quite a while now.

My (and others probably) issue is the fact that when I allow notifications on your "Always On AMOLED" screen I can no longer put the phone in my pocket because it keeps turning no when the notification is touched.

In my opinion there should be an **option to enable/disable notifications from being activated by touch**, so that it will not turn the screen on in your pocket.

If you need clarification, please contact me at lorenhpearson@gmail.com.

Thank you and best regards!

Loren Pearson

**Comment by rosenpin** [comment]
You can enable pocket mode, this will lock the screen and prevent accidental touches while the device is in your pocket
