### ISSUE TITLE
"Raise To Wake" Flashing Lock Screen for .5ish seconds after 10 second timeout.

### ISSUE THREAD

**Issue by tokotchd** [rosenpin/AlwaysOnDisplayAmoled#1471]
App runs perfectly otherwise, but when raise to wake is activated, the end of the 10 second raise to wake timer flashes the whole lock screen for a half ish second, which is bright and distracting and ruins any battery saving that might have been done with the 10 second partial AMOLED activation.  

Done with app version 0.96 beta, Galaxy S6, Android 6.0.1.  Tried turning off developer screen animations (for the tube fadeout) and many iterations of options but bug persists.

**Comment by rosenpin** [comment]
Sorry for the late response, can you please update to the latest beta update and let me know if the problem persists?

https://play.google.com/apps/testing/com.tomer.alwayson
