### ISSUE TITLE
Oneplus 3 screen off gestures

### ISSUE THREAD

**Issue by benisoliver** [rosenpin/AlwaysOnDisplayAmoled#1486]
I know that these are screen off gestures and with this app the screen is never off but it would be very useful if these gestures would work while the always on service is enabled.

**Comment by rosenpin** [comment]
You can enable some gestures in the 'Gestures & shortcuts' section (more gestures if you are using the PRO version of the app)
Let me know if you have any specific request for a screen off gesture.

There is currently gestures to:

- Turn the screen on
- Say the current time, notifications and battery status out loud
- Toggle flash light

In addition to this, you can control music playback by enabling 'Show music controls' in the 'Customize watchface' section. (music controls buttons will pop up when music is playing)
