### ISSUE TITLE
Raise to Wake does not work normally.

### ISSUE THREAD

**Issue by droidtub** [rosenpin/AlwaysOnDisplayAmoled#1516]
Raise to wake feature does not work fine. Sometime are good, but mostly the screen does not wake when raising phone. Please fix this.

**Comment by rosenpin** [comment]
Please join the beta test program and update the app.
There is now an option to adjust the raise to wake sensitivity

https://play.google.com/apps/testing/com.tomer.alwayson

**Comment by hdsplash** [comment]
@rosenpin : when will you push this option's commit into Github?

**Comment by hdsplash** [comment]
@rosenpin : when will you push this option's commit into Github?

**Comment by rosenpin** [comment]
@hdsplash 
Sadly, this repo is no longer actively maintained since other "developers" started re-publishing my app to the play store with ads.
I might start updating it again in the future.
