### ISSUE TITLE
LayoutParams parameters

### ISSUE THREAD

**Issue by droidtub** [rosenpin/AlwaysOnDisplayAmoled#1582]
Hi @rosenpin,
Actually this is not an issue. 
1. I have wondered what do these params: 2003, 65794 mean in:
`WindowManager.LayoutParams lp = new WindowManager.LayoutParams(-1, -1, 2003, 65794, -2);
 lp.type = WindowManager.LayoutParams.TYPE_SYSTEM_ERROR;`

2. Could you explain how First Fragment works in Intro activity for ACTION_MANAGE_OVERLAY_PERMISSION? Your way works fine, but I don't get your idea.
Regards.

**Comment by rosenpin** [comment]
1. 2003 is the type (could alternatively use WindowManager.LayoutParams.TYPE_SYSTEM_ALERT)
65794 is the flag
-2 is the format

Read more about it here
https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html

2. I don't quite understand the question, the app requires MANAGE_OVERLAY_PERMISSION, ```ACTION_MANAGE_OVERLAY_PERMISSION``` is the intent action to launch the settings activity on the manager overlay permission for the specified package name

Let me know if you have any other questions

**Comment by droidtub** [comment]
Thanks for your quick answer.
1. So what flag, format correspond to 65794 and -2, relatively?
2. Why do you add and then remove view, what is meaning of this view: 

'WindowManager.LayoutParams lp = new WindowManager.LayoutParams(-1, -1, 2003, 65794, -2);
 lp.type = WindowManager.LayoutParams.TYPE_SYSTEM_ERROR;
 View view = new View(context);
 ((WindowManager) context.getSystemService(WINDOW_SERVICE)).addView(view, lp);
((WindowManager) context.getSystemService(WINDOW_SERVICE)).removeView(view);'

and the Go button is invisible, just set it's onClickListener in catch exception, so how it can be visible and clicked for the first time?

**Comment by rosenpin** [comment]
> So what flag, format correspond to 65794 and -2, relatively?
I don't remember what each flag and format correspond to individually, but combined it sets the view to appear on the top of the screen and touchable without passing touch to underlying views

> Why do you add and then remove view, what is meaning of this view:
This is a "test" view, this chunk of code exists in a try block if I am not mistaken, if the code passes successfully, then the app has the required permission, if it fails, it does not.
It's a part of the intro.
