### ISSUE TITLE
Clock moves off the screen

### ISSUE THREAD

**Issue by adiasandre96** [rosenpin/AlwaysOnDisplayAmoled#165]
In my OnePlus 3, the clock moves out of the screen. When Always On service starts right at the top (001), then moves randomly going out of the screen (002, 003).
![001](https://cloud.githubusercontent.com/assets/18745609/17361723/c21ebaa0-5969-11e6-942f-894ffc88c46b.png)
![002](https://cloud.githubusercontent.com/assets/18745609/17361729/cdbc087c-5969-11e6-836a-a10816feebc1.png)
![003](https://cloud.githubusercontent.com/assets/18745609/17361738/d4324180-5969-11e6-8900-a8edbf05573b.png)

Thanks for the great work, I've helped you translating all to Portuguese!

Version: 0.9
Build: 132

**Comment by rosenpin** [comment]
This issue was already fixed in version 0.9XY build 133.
Make sure you have updated the app.
