### ISSUE TITLE
Always On Display AMOLED always on issue

### ISSUE THREAD

**Issue by kvchau** [rosenpin/AlwaysOnDisplayAmoled#1964]
I'm using XiaoMi Mi3, this app is great app but it keep on turning on & won't turn off the screen. It should be raise to wave, then only will wake up but it's not, it keeps on forever.
I already set the "stop always on automatically rules to disabled", "raise to wave" to enabled, "always on work for charging & discharging" & "always on display works for battery 20% & above"; but the screen still always on regardless wave or not waving on the proximity sensor.
Please fix this issue as soonest because it drain my phone battery super fast from 100% to 35% for 6 hours (this is unacceptable)
Thanks

**Comment by kvchau** [comment]
besides the above, the app will be kill if i clear cache or memory from the build in MIUI cleaning function.
please improve this as keep the app in persistent which won't be kill.
Thanks

**Comment by rosenpin** [comment]
Try uninstalling then reinstalling the app.
I can't prevent the app from being killed when you clear RAM.
Take my tip though, you should never clear your phone RAM, Android's memory management is very powerful and by clearing the memory manually you are only slowing down your device.

**Comment by kvchau** [comment]
thanks for your swift response, well noted on not clear the RAM. :)
but, unfortunately, I have reinstalled twice, but it still the same.. the Always on still keeps turn on regardless waving the proximity sensor :(

**Comment by kvchau** [comment]
Hi, Don't know what happen, now it works but... just 2-3 times then it not working anymore (the always on seems stop itself), i need to reopen the app then it back to function again...
besides, my phone will be off at night... when i turn on the phone, the always on stop working.. i need to open the app then only work again... :(

**Comment by kvchau** [comment]
I'm sorry, i getting frustrated. now it back to the previous issue again... it keeps on turning on regardless waving on the proximity sensor, now my battery from 100% draining to 93% within 10 minutes :'(
besides the issue, it having other issues below:
1. sometimes it works for only 2 - 3 times then it stop... the always on not functioning regardless waving the sensor or not.
2. when notification come, the always on keep turning on won't stop.
3. if I press power button for turn off the screen since it keep on turning on, after i press the power button, the always on won't work anymore.
4. if i restart my phone, the always on won't work anymore although I have locked the app with the service enabled from the app in the memory not being kill & optimized. I need to reopen the app again, then it works again.

**Comment by rosenpin** [comment]
It's really difficult for me to understand what you are trying to say.
Please try to join the beta program if you haven't already and let me know if it fixes some of your issues

https://play.google.com/apps/testing/com.tomer.alwayson

If it still doesn't work please try to explain the issues you are experiencing more clearly and in more details.

**Comment by kvchau** [comment]
thanks. can you tell me how to configure the greenify to save battery?
which setting need to enabled & do i need to put always on in the hibernate list. 
I tried so many ways.... regardless put in hibernate or not, 
1. sometimes I waving my proximity sensor, then the always on turn on, but after 1, 2 minutes when i waving on proximity sensor, no response at all (means the always on not turn on)
2. sometimes I waving on proximity sensor, then it won't turn off the screen & it will keep show the always on & battery drain super fast.

I believe I already provide clear details enough from the past threads till recent, you need to simulate the issue as a developer.
thanks...
i am using v0.9.8.1 beta

**Comment by kvchau** [comment]
Hi Dear Developer, Any update on my reported case?

**Comment by rosenpin** [comment]
Sorry, I can't reproduce this bug.
MIUI might be killing the app without asking you.
Try locking the app so MIUI won't kill it.

**Comment by kvchau** [comment]
Yes, I have lock the app.
MIUI not killing it anymore, but the problem that I facing not because of MIUI killing it.
Before I go thru the problem, I providing you the setting:

1. Automatic Rules:
a. Stop Delay - Disabled
b. Always on Charge - Both Charging & Discharging
c. Battery level for Always On - 20% & higher

2. Ambient Display & Raise to Wake:
a. Raise to wake - Enabled
b. Notification wake - Enabled
c. Pick from table - Disabled

Understood that the Ambient Display & Raise to Wake will overwrite the Automatic Rules.
but, If based on the above setting which "Stop Delay" has set to ""Disabled", it should not overwrite since it already disabled.

So, the problems that I facing are:

1. After installed 0.9.8.1 Beta, turn off the screen by pressing power button; the Always On sometimes works fine which is the screen off, then when I waving on Proximity Sensor, it wake up & never ever will off the screen & it keep looping wake up showing the Always On. this causing battery drain very fast & device get hot.

2. Related to point 1, but slightly different. After installed 0.9.8.1 Beta, turn off the screen by pressing power button, it will turn off screen for few seconds then it wake up automatically & keep lopping showing the Always On, & screen won't turn off. this causing battery drain very fast & device get hot.

3. Sometimes it works well which Always On won't wake up... but when Notification come with/without LED blinking from my phone, the Always On keep wake up & looping causing the screen won't turn off & it causing battery drain fast & device get hot.

4. Sometimes, when I waving on Proximity Sensor, the Always On won't wake up.

5. Sometimes, when I waving on Proximity Sensor, the Always On wake up & will never ever turn off the screen & it keep looping showing the Always On although I did not waving on Proximity Sensor.

6. Sometimes, the Always on seems stop (waving on Proximity Sensor no response), so I press power button to wake my screen on, it should show Always On, but it show my phone Lockscreen. I need to open the app again then it only back to function (I have locked the app from killing by Memory).

Hope above are clear for you.

Thanks

**Comment by cziberez** [comment]
I have Redmi Pro with Miui 8 installed
I have experienced the same as well. To fix:

1) Go to the Settings ->About phone
Touch sometimes the MIUI version to enable developer options on your phone
After that go back to System -> Developer Options
Scroll Down and Turn off MIUI memory optimization

![screenshot_2017-02-13-20-40-32-257_com android settings](https://cloud.githubusercontent.com/assets/18663813/22900207/c9880884-f22d-11e6-891a-98bfe36cd9eb.png)

2) Go back to Settings -> Battery & performance -> Manage apps battery usage 
Set the MIUI optimization on:

![screenshot_2017-02-13-20-36-50-868_com miui powerkeeper](https://cloud.githubusercontent.com/assets/18663813/22900292/1d7d5822-f22e-11e6-9f0a-3e2ac9ca7b50.png)


3) Then -> Choose apps
Select the Always On AMOLED and Always On AMOLED Plugin and switch both to No restrictions and Allow Background location

![screenshot_2017-02-13-20-36-38-841_com miui powerkeeper](https://cloud.githubusercontent.com/assets/18663813/22900332/48a851e6-f22e-11e6-8ed8-79f8cc5d8163.png)
![screenshot_2017-02-13-20-36-26-369_com miui powerkeeper](https://cloud.githubusercontent.com/assets/18663813/22900333/48a8fa42-f22e-11e6-908d-c694ace97238.png)

**Comment by cziberez** [comment]
Another thing: If you can Root your phone use Greenify

**Comment by kvchau** [comment]
thanks cziberez

actually before you told me, I already did the same as yours.. problem still persists. my concern is not on the MIUI memory kill the app.. my concern is the app itself having problem.
I find out it might programming logic incorrect..

how can be raise to wake overwrite the automatic rules...
if i did not set the raise to wake, & only set the automatic rules to disabled... the always on will forever there without turn off the screen. If i set the automatic rule to stop delay as 1 min, it still will show the screen sometimes... & sometimes it close & show lockscreen & the always on won't work anymore. i need to rerun the app although i had lock the app in memory.
if I set the raise to wake enabled, & automatic rule to disabled... the always on sometimes will turn off, sometime it keep looping & never ever turn off & cause battery drains regarding turn off the MIUI optimization or not...

sometimes, even the always on turn off itself, & when i waving on proximity sensor, it won't work, sometimes it works but keep looping & will not turn off screen...

i think the programming logic should be... if the automatic rule set to disabled, & using raise to wake (enabled), when wave 1 time, then screen wake up then couple of seconds it should turn off the screen & put the app as sleep/hibernate, when waving on proximity sensor again regardless waving after 30 minutes, or 1 hour, the screen will turn on again & show always on display...

i believe this should control the proximity sensor in the code level...
thanks

**Comment by kvchau** [comment]
Thanks cziberez.
let's me try your way. I will monitor it & provide update again.

**Comment by kvchau** [comment]
Hi cziberez,

You are awesome & amazing!!
I follow your guidance, it 90% solved the issue...
10% the issue still persists which it happens intermittently as I mention above:
1. Sometimes it will keep looping & screen wake up regardless waving on proximity sensor or not
2. When notification come, sometimes it will keep looping showing the Always On.

but, may be in 10 times, it happens 3 times. it is much more better than previous which happens frequently (9 times out of 10 times)...

Thank you so much for your great guidance...

**Comment by kvchau** [comment]
But cziberez,

I have a question, since everything are off for MIUI/Memory Optimization, does it consumes battery (drain faster)? because my phone not rooted & i did not install greenify.
my phone cannot root, because I have corporate email setting in my phone & corporate policy is not allowing phone being rooted (for android) & jailbreak (for iOS) else the email account will be  blocked.

**Comment by cziberez** [comment]
I'm glad to help :)

Maybe proximity sensor not work properly in this version (not tested or maybe just with Xiaomi)
Well I have Fingerprint unlock, so doesn't have that problem but if you hit the home button it's always disapear for me. What MIUI version you have?

MIUI memory optimization pre-allocate some of you ram I didn't notice any difference with on and off just that I have more free ram sometimes.

If you want to root it then make a new MIUI account then go to http://www.en.miui.com/unlock and ask permission for unlock the bootloader (write that you want to install TWRP recovery and root acces)

After some days you got a unlock acces and unlock the phone then follow these steps after unlocked bootloader:
https://forum.xda-developers.com/redmi-note-3/how-to/method-miui-8-unlock-bootloader-twrp-t3529458

**Comment by kvchau** [comment]
Thanks alot cziberez.

I'm using MIUI 8.1.6.0 Global Stable ROM, Android 6.0.1

Just find out if I did not touch my phone couple of minutes/hours (just leave it on my desk), suddenly the Always On will turn on the screen & keep looping for 10 times or sometimes even more than 10 times, then it turn off the screen & sometimes not turning off the screen & it will keep looping.

Not sure is it due to MIUI/XiaoMi itself or the app still unstable/un-support for Android 6

**Comment by rosenpin** [comment]
@cziberez Thanks a bunch for the great explanation!
I wasn't aware to all those changes Xiaomi chose to make to Android.
This explains a lot of complaints I received from Xaiomi users about my app.

**Comment by kvchau** [comment]
cziberez,

issue seems not resolved... i don't know what happens... I no touch the phone... the always on keep looping & screen keep wake up... & battery drain very fast from 100% to 91% within 30 minutes & the device get hot.
May I know do I need to lock the app in memory which not being kill by the task killer?
Kindly please advice....

@rosenpin 
Kindly please do not close this issue as not yet solved. please reopen the case until it solve & stable.

Thanks

**Comment by cziberez** [comment]
Well I tested some always on screens found one which works really well. It uses features like Greenify to do. One thing is: it doesn't have so much customization.

@kvchau
Did you add the permissions in the Security app? Like autostart, notification? Which rom? Global, Chinese or Multilang?

**Comment by kvchau** [comment]
@cziberez 
Yes, I did added the permission for autostart, notification, device administrator, locked the app, turn off optimization as per your advice, no restriction & allow for battery. but issue still persist.. now keep turn on, won't screen off & now my battery become 81%... :'(
Global ROM as it sent to me previously via Update app in the phone.
this is the ROM
miui_MI3WMI4WGlobal_V8.1.6.0.MXDMIDI_5984da4175_6.0

Thanks

**Comment by cziberez** [comment]
Sorry for the late answer but can't reporoduce your problem at the moment. I tested it on my gf's Galaxy S7 Edge as well then I just realised that I turned off the original lock screen under the Fingerprint & Security tab to make it work on my Redmi.

Weird but when I turned it on it happend once but not anymore. I have a Chinese version of MIUI rom (Redmi Pro doesn't have offical Global) with Xiaomi.eu modify for European usage (translations, apps, etc.)

Btw. you feel the battery loss so well with Always on screen and if you don't have a 4050 MAh battery like me then you can notice that 1-2 hours loss during usage (Samsung is losing around 5-10% with a full charge)

**Comment by kvchau** [comment]
Yup... yesterday the last i saw & provided the info on my battery is 81%. when I woke up this morning, the phone is off because battery become 1% 
:(
& my device getting super hot.
For time being, I already uninstall the app, hope there will be a fix for all this issue in the next release because I love this app compared with other same app developed by other developer such as Glance Plus. I use Glance Plus before, it have no issue at all & work perfect, but the only problem is battery drains super fast which same as Always On, it caused my battery drain till 1% as well in a night with a full charge. :(

**Comment by kvchau** [comment]
Hey Guys,

I saw there is a new version for Always On 0.9.8.2 Beta.
I tried to installed it, seems works well compare with 0.9.8.1
but, not sure... I need to monitor it again for few days...

please do not close this ticket yet...
thanks...

**Comment by cziberez** [comment]
Awesome! I don't know what caused you the problem, maybe the rom, maybe the MIUI, maybe something else

**Comment by kvchau** [comment]
I also don't know. So far I have monitor for 4 hours, seems working perfect.. I restarted my phone, the Always On will autostart... I no need lock the app anymore... & all the previous issue seems no more happens... but.. I can't conclude yet, let monitor a few days especially for the night. I would need to see how about the battery consumption.
Tomorrow MIUI will release MIUI 8.2, hopefully after I upgraded it, it won't bring issue to Always On.
As I would like to update the MIUI 8.2 because some features are quite nice.
Hopefully this 0.9.8.2 Beta no more issue for me :)

anyway, please keep this ticket open... thanks & sorry of troublesome you guys because cannot close the ticket

**Comment by cziberez** [comment]
Your phone has LCD or Amoled display?

**Comment by kvchau** [comment]
Only LCD....

**Comment by kvchau** [comment]
Battery slightly improved, but still consider as bad.... from 96% drain until 36% when I check after I woke up compared with the previous version, it from 100% to 18%.
May be I should deactivate/disabled the Always On during bed time..
let's see... because never use this feature, not sure having issue or not.

**Comment by kvchau** [comment]
it dun have an option to disabled the Always On from certain time to certain time... :(
I can't set the automatic rules, because Raise to wake in enabled & it overwrite the automatic rule... 
sigh...

**Comment by kvchau** [comment]
after a day... issue happens again.... when notification came, (I set the wake always on for notification as disabled), but the always on keep looping turning on the screen...

**Comment by kvchau** [comment]
this is weird again.. all previous issue... come back again..... autostart cant' work anymore. (means service won't start)... screen keep turn on regardless waving proximity & received notification...

:(

**Comment by kvchau** [comment]
FYI, I not yet update to MIUI8.2 as not yet receive via OTA...

**Comment by rosenpin** [comment]
Is the issue still present in the latest update?

**Comment by kvchau** [comment]
Hi
Sorry of late response. You may close this ticket.
Thanks
