### ISSUE TITLE
Paywalling free and open source resources

### ISSUE THREAD

**Issue by baconicsynergy** [rosenpin/AlwaysOnDisplayAmoled#199]
This has no place in F-Droid. Obfuscating FLOSS resources via a paywall within a GPL licensed software is shameful.

**Comment by rosenpin** [comment]
The app is free to use.
There are IAP so users may donate if they want to and so I can continue to work on the app as much as I do.
The "supporters only" features include fonts (that are available for commercial use), watchfaces (that I created myself), and custom gestures (also created myself).
If you can't afford to pay the **1$**, the price to unlock all the features inside the app, you don't have to support the development.

**Comment by baconicsynergy** [comment]
As you wish. I shall file a report to have this software removed from the main F-Droid repository
