### ISSUE TITLE
Overheats and drains too much battery on some devices

### ISSUE THREAD

**Issue by rosenpin** [rosenpin/AlwaysOnDisplayAmoled#20]
Should find a way to lock the screen when not in use.
As well as maybe getting doze to work while the app is running on rooted devices.

Kind or related to  #22

**Comment by jdrescher2006** [comment]
Hello @rosenpin,
I have one suggestion to reduce battery drain.
If  AMOLED anti burn-in is activated, the clock is pushed over the screen every 20 seconds.
This triggers a display wakeup event every time, which will consume energy.
I think it would be sufficient to push the clock every one minute over the screen.

**Comment by rosenpin** [comment]
Thanks for the suggestion @jdrescher2006 
I'll add an option to customize the delay soon

**Comment by rosenpin** [comment]
Added a battery save mode in the latest beta
