### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by JoshuaDR** [rosenpin/AlwaysOnDisplayAmoled#2000]
I like the app but there is just one thing that happen. Have been using the app for months but it only happen once (Just know). The Always on screen is showing but when I close it to open the phone only a black screen shows. I lock my phone (Using the power button) to try it again but the same thing happens. I tried opening via Power button or home button but it is still the same. To fix this I removed the battery and restart the phone. This will be a major issue for people with unremovable battery.

Holding the power button doesn't work. Android will show options like "Power Off", "Restart" and more, but nothing occur.

**Comment by JoshuaDR** [comment]
I use a Samsung J7 2016.

**Comment by rosenpin** [comment]
That's very weird, the black screen should automatically disappear when your screen is locked or when the lockscreen is dismissed.
This might be an issue with Samsung's implementation of this API.
In the future if this happens again, you can long press the power button for 15-20 seconds, this will restart your device.
Please let me know if it happens again.

**Comment by hypercross** [comment]
Actually, this is happening to me right now and I have S6 edge which has an unremovable battery... And looks like I can't use the phone until the battery dies

**Comment by rosenpin** [comment]
If this happens again, you can long press the power button for 15-20 seconds (maybe even more), this will force restart your device.

**Comment by hypercross** [comment]
Thanks for the tip... didn't know that...

**Comment by JoshuaDR** [comment]
Is it because I disable "Show Persistent Notification" which could be the cost or this has nothing to do with the blackscreen.
