### ISSUE TITLE
[Weather] (temperature)°bent except for (temperature)°C

### ISSUE THREAD

**Issue by cziberez** [rosenpin/AlwaysOnDisplayAmoled#2012]
I'm using the Hungarian translation on my Xiaomi Redmi Pro Prime phone and it's awesome (purchased as well).
But there is some translation error I think, because it says (temperature)°bent expept for (temperature)°C
![screenshot_2017-02-12-19-13-47-126_lockscreen](https://cloud.githubusercontent.com/assets/18663813/22864782/c829a014-f157-11e6-9340-1b998f2ac9f2.png)
Like this. So Celsius letter C probably misstyped.

**Comment by rosenpin** [comment]
It should be saying 3° in...
What does bent mean in your language?

**Comment by cziberez** [comment]
Inside indoor 😀
It's hard to implement prepositions in Hungarian (Facebook tried with 50% of succes)

**Comment by rosenpin** [comment]
Oh, I see, how would you translate it?
If there is a simple way to translate it I will update the translation

**Comment by cziberez** [comment]
(temperature)° (cityname) "térségében"
Or just simply change the "bent" to a "C" letter and it's gonna be mean Celsius in the future
As you wish and thanks :)

**Comment by rosenpin** [comment]
OK, will fix in the next update.
Thanks for the feedback! :)

**Comment by cziberez** [comment]
No problem
Thanks for the debug :)
