### ISSUE TITLE
Proximity wake and power button

### ISSUE THREAD

**Issue by fredericseiler** [rosenpin/AlwaysOnDisplayAmoled#2108]
Hi,

First of all, thanks for this great app !

I want to use the "Proximity wake" option (I loved this functionality on Windows Phone), but when I wave over the phone to check for new notifications, and I want to wake up the phone to see the notification details, the power button turns off the display instead of showing the lock screen. I have to press the power button again to show the lock screen.

Is there something you can do to fix that ?

**Comment by rosenpin** [comment]
Thanks for the feedback!
I agree with you on this issue.
Sadly, there is no API for interpreting power button clicks, meaning this will be impossible to implement without root access and undocumented API.

Sorry but I won't be able to implement this feature.
You can double tap the screen to wake it up though.

**Comment by fredericseiler** [comment]
What about [android.permission.PREVENT_POWER_KEY](http://stackoverflow.com/questions/3703071/how-to-hook-into-the-power-button-in-android/10365166#10365166) ?

**Comment by rosenpin** [comment]
Seems like this API only works on Cyaongenmod based ROMs.
I tested this code on my OnePlus 3T and it doesn't show any sign of working whatsoever.
It doesn't recognize a power button press, not to mention preventing the screen from being locked by the click.
Again, I'm sorry for not being able to support this, it could be pretty awesome if developers could interpret power button click but also very dangerous if you think about it.
It's a wise decision to not include an option to prevent the power button from working for 3rd party applications.

**Comment by fredericseiler** [comment]
My bad, I didn't see [this comment](http://stackoverflow.com/questions/3703071/how-to-hook-into-the-power-button-in-android/10365166#comment38038609_10365166)...

Anyway, when I don't use the "Proximity wake" option, if I press the power button when the sleeping screen is on, the phone wakes up. What's the difference between the two modes ?
