### ISSUE TITLE
System UI crashed after plugin installed

### ISSUE THREAD

**Issue by Slitt** [rosenpin/AlwaysOnDisplayAmoled#217]
Not running a custom ROM, phone is rooted. Currently running 5.0.2.

> 
> I managed to fix the issue, but this is a pretty crucial problem that might cause some people inconvenience.
> 
> I am using a Galaxy S6 (SM_G920A).
> 
> I insralled the Always On AMOLED apk and started the service and installed the hardware button disable plugin for the app. After installing, the Always On AMOLED app process crashed and my screen shut off. Since the plugin was also installed, I couldn't turn on the screen or enter recovery mode. My phone was pretty much in a bricked state, but the notification LED would still blink.
> 
> After calling myself from a different phone, the screen finally lit up, showing that the System UI stopped, and from there I could disable the Always On AMOLED service.
> 
> I just wanted to let you know about this issue. Sorry for the inconvenience.
> 
> 

-

Device info:
---
<table>
<tr><td>App version</td><td>0.9.1.97</td></tr>
<tr><td>App version code</td><td>147</td></tr>
<tr><td>Android build version</td><td>G920AUCU1AOCE</td></tr>
<tr><td>Android release version</td><td>5.0.2</td></tr>
<tr><td>Android SDK version</td><td>21</td></tr>
<tr><td>Android build ID</td><td>LRX22G.G920AUCU1AOCE</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>zeroflteatt</td></tr>
<tr><td>Device model</td><td>SAMSUNG-SM-G920A</td></tr>
<tr><td>Device product name</td><td>zeroflteuc</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7420</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>showampm</td><td>false</td></tr>
<tr><td>google_now_shortcut</td><td>false</td></tr>
<tr><td>double_tap_action</td><td>1</td></tr>
<tr><td>stop_delay</td><td>0</td></tr>
<tr><td>enabled</td><td>true</td></tr>
<tr><td>back_button_action</td><td>0</td></tr>
<tr><td>camera_shortcut</td><td>false</td></tr>
<tr><td>persistent_notification</td><td>true</td></tr>
<tr><td>greenify_enabled</td><td>true</td></tr>
<tr><td>permissiongrantingscreen</td><td>true</td></tr>
<tr><td>watchface_clock</td><td>1</td></tr>
<tr><td>proximity_to_lock</td><td>false</td></tr>
<tr><td>volume_keys_action</td><td>0</td></tr>
<tr><td>startafterlock</td><td>true</td></tr>
<tr><td>screen_orientation</td><td>vertical</td></tr>
<tr><td>swipe_up_action</td><td>0</td></tr>
<tr><td>doze_mode</td><td>false</td></tr>
<tr><td>notifications_alerts</td><td>false</td></tr>
<tr><td>watchface_battery</td><td>0</td></tr>
<tr><td>watchface_date</td><td>1</td></tr>
<tr><td>notifications_alerts_preview</td><td>true</td></tr>
<tr><td>auto_brightness</td><td>false</td></tr>
<tr><td>has_soft_keys</td><td>false</td></tr>
<tr><td>disable_volume_keys</td><td>true</td></tr>
<tr><td>rules</td><td>always</td></tr>
<tr><td>exit_animation</td><td>1</td></tr>
<tr><td>movement_style</td><td>2</td></tr>
<tr><td>battery_rules</td><td>0</td></tr>
</table>

**Comment by rosenpin** [comment]
Can you update the app to the latest version and let me know if the issue persists?

**Comment by Slitt** [comment]
I updated the app and it works perfectly now. Thank you so much!

**Comment by rosenpin** [comment]
Awesome! Thanks for letting me know :)
