### ISSUE TITLE
Always on Screen flashes before starting when Pocket mode is on

### ISSUE THREAD

**Issue by JoshuaDR** [rosenpin/AlwaysOnDisplayAmoled#2229]
There is an issue when you turn the Proximity sensor (Pocket mode) on. It will cause the always on screen to flash before starting. Turn it off will resolve the issue. 

I am using a samsung galaxy j7 2016 by the way. This may help other people who also has the issue.

**Comment by rosenpin** [comment]
Is the issue still present in the latest release?
