### ISSUE TITLE
After working twice, has to be restarted

### ISSUE THREAD

**Issue by Recharged** [rosenpin/AlwaysOnDisplayAmoled#225]
When I open the app, it works fine twice for me to unlock my phone, but then I have to reopen the app itself for the service to start again. The "Always On is Running" notification is still there, however, it doesn't work. Highly repeatable. 

-

Device info:
---
<table>
<tr><td>App version</td><td>0.9.1.97</td></tr>
<tr><td>App version code</td><td>147</td></tr>
<tr><td>Android build version</td><td>7738569c59</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>cm_falcon-userdebug 6.0.1 MOB30J 7738569c59 test-keys</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>falcon_umts</td></tr>
<tr><td>Device model</td><td>Moto G</td></tr>
<tr><td>Device product name</td><td>cm_falcon</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>double_tap_action</td><td>1</td></tr>
<tr><td>google_now_shortcut</td><td>false</td></tr>
<tr><td>enabled</td><td>true</td></tr>
<tr><td>stop_delay</td><td>0</td></tr>
<tr><td>back_button_action</td><td>0</td></tr>
<tr><td>camera_shortcut</td><td>true</td></tr>
<tr><td>persistent_notification</td><td>true</td></tr>
<tr><td>greenify_enabled</td><td>true</td></tr>
<tr><td>font</td><td>0</td></tr>
<tr><td>permissiongrantingscreen</td><td>true</td></tr>
<tr><td>watchface_clock</td><td>1</td></tr>
<tr><td>proximity_to_lock</td><td>true</td></tr>
<tr><td>volume_keys_action</td><td>0</td></tr>
<tr><td>screen_orientation</td><td>vertical</td></tr>
<tr><td>startafterlock</td><td>true</td></tr>
<tr><td>swipe_up_action</td><td>0</td></tr>
<tr><td>doze_mode</td><td>false</td></tr>
<tr><td>watchface_date</td><td>1</td></tr>
<tr><td>watchface_battery</td><td>0</td></tr>
<tr><td>notifications_alerts</td><td>true</td></tr>
<tr><td>notifications_alerts_preview</td><td>true</td></tr>
<tr><td>auto_brightness</td><td>true</td></tr>
<tr><td>has_soft_keys</td><td>true</td></tr>
<tr><td>rules</td><td>always</td></tr>
<tr><td>disable_volume_keys</td><td>true</td></tr>
<tr><td>brightness</td><td>15</td></tr>
<tr><td>exit_animation</td><td>1</td></tr>
<tr><td>battery_rules</td><td>30</td></tr>
<tr><td>movement_style</td><td>2</td></tr>
</table>

**Comment by Recharged** [comment]
Ironically enough, disabling the persistent notification has seemed to help.

**Comment by rosenpin** [comment]
Thanks for letting me know!
Sorry about the late reply, but could you please send me a video of the issue when it happens?
It might help me understand the source of the bug.

**Comment by rosenpin** [comment]
No response.
Outdated version.
Closing
