### ISSUE TITLE
Home button to unlock never working

### ISSUE THREAD

**Issue by mmkthecoolest** [rosenpin/AlwaysOnDisplayAmoled#2282]
I have a non-rooted Samsung Galaxy s6 that runs Android 7. The home button to unlock feature stopped working after I restarted my phone. I have tried everything such as uninstalling the app restarting then reinstalling and it still won't work. Please fix this.

**Comment by rosenpin** [comment]
What android version are you using? What version of the app are you using?

**Comment by mmkthecoolest** [comment]
Android 7.0 (Samsung stock). the app version is 0.9.9.3 build 902

**Comment by rosenpin** [comment]
This feature is deprecated in the latest beta version.
Users should now use the simulated home button to unlock.
