### ISSUE TITLE
Move widget automatically does not work on Lenovo P2 

### ISSUE THREAD

**Issue by Mbharath003** [rosenpin/AlwaysOnDisplayAmoled#2367]
Hi, the automatically move widget does not automatically move on the lenovo p2. Can you have a look?

**Comment by Mbharath003** [comment]
Just realized that the widget only moves like 1 or 2 millimeters.. It is more or else around the same place which would cause burn in if it was on all the time. 
Could you have a look and make it move around more? Or farther apart? 

1)timer at which widget moves. Like move evry 5 secs. 
2) move father apart from center to bottom, bottom to top, random (all over the screen)

**Comment by rosenpin** [comment]
Can you send me a screenshot of the always on display while it's running?
If you have a lot of elements on the screen the movement will stay minimal
