### ISSUE TITLE
[REQ] Set rotation via tasker

### ISSUE THREAD

**Issue by chrisvella** [rosenpin/AlwaysOnDisplayAmoled#2371]
I would like the ability to not only turn AODA on and off via tasker, but also set the orientation. This would allow me to use my phone like a clock when I enable wireless charging. Thanks.

**Comment by rosenpin** [comment]
That's a cool feature!
Sorry it took me so long to respond, I'll add it soon

**Comment by rosenpin** [comment]
Done, will be added in the latest beta

**Comment by chrisvella** [comment]
Awesome thank you :)

**Comment by chrisvella** [comment]
Thank you for the patch. I have it setup as a digital clock when I put my phone on wireless charge. Looks really awesome :)

Just a heads up I sometimes get errors from the application about problems enabling it. It also can crash when I try and unlock the device (reasonably infrequent).

Thanks again!

**Comment by rosenpin** [comment]
Thanks for the feedback.
I wrote the Tasker plugin part of the app about a year ago, the app has changed a lot since then, I should probably rewrite some of it at some point
