### ISSUE TITLE
Can't turn screen on by pressig home button on Galaxy J2

### ISSUE THREAD

**Issue by shanidevious** [rosenpin/AlwaysOnDisplayAmoled#2379]
It works well on Galaxy J2 but there is one issue. I can turn screen on by using power button but **it won't turn on by pressing home button** or by swiping up on screen(I set it up in app settings).

**Comment by rosenpin** [comment]
You can enable the simulated home button in the gestures & input settings.

**Comment by shanidevious** [comment]
Yes currently I am using that feature, but if you could enable screen on through home button in this app it would be great. Anyways, I am really appy with it. Good work indeed! Thanks.
