### ISSUE TITLE
Removed From The Play Store By Error

### ISSUE THREAD

**Issue by rosenpin** [rosenpin/AlwaysOnDisplayAmoled#2400]
### Update: The app was re-instated!!
Thanks everyone so much for all the help getting this to Google's attention! I really believed it was impossible when I first posted this. You are all awesome!

I received the following email from the Google Play team this morning, a few hours later my app was re-published. 

> Hi,
> 
> Thanks for contacting the Google Play team.
> 
> Action required: Submit your app
> 
> In order to show your app (com.tomer.alwayson) on Google Play, please submit your app again: 
> 
>     Sign in to your Play Console.
>     Select your app.
>     Select Store presence > Store listing.
>     Click Submit update or Resubmit app.
> 
> If the submit button is grayed out, you can make a minor change to your store listing to activate the button. For example, add a space after your app title and then delete it. Once the button turns blue, you can submit your update.
> 
> If you're an AdMob publisher, please contact the AdMob team to re-enable ad serving.
> 
> Before republishing your apps, you may also want to double check that your app complies with all Developer Program Policies. If you need additional help, you can also visit the Play Console Help Center or the Android Developers website.
> 
> Thanks for your continued support of Google Play!
> Regards,
> Annie
> The Google Play Team

Edit: [Android Police posted a fantastic article about the situation, explaining it in great detail](https://www.androidpolice.com/2018/10/17/dmca-failure-play-store-automated-takedowns-hit-indie-app-always-display-amoled/)

On October 11th Google removed Always On AMOLED from the Play Store due to an error in their DMCA system.

It seems like a company called "Flipkart" issued a DMCA notice against several replicas of their app and somehow my app was mangled in the situation and removed from Google Play Store.

I tried contacting Google and explain the situation but for no avail. I will continue to attempt in contacting Google but sadly it seems that they are very unwilling to provide any kind of support for independent developers on their platform.

The following is the original Email I received from Google about the DMCA notice:
 
> This is a notification that your application, Always On AMOLED - BETA, with package ID com.tomer.alwayson, has been removed from Google Play.
> 
> REASON FOR SUSPENSION: Alleged copyright infringement (according to the terms of the Digital Millennium Copyright Act).
> 
> All violations are tracked. Serious or repeated violations of any nature will result in the termination of your developer account, and investigation and possible termination of related Google accounts. If your account is terminated, payments will cease and Google may recover the proceeds of any past sales and the cost of any associated fees (such as chargebacks and payment transaction fees) from you.
> 
> Please review the Developer Distribution Agreement and Developer Program Policies to ensure your applications are compliant with our policies.
> 
> The DMCA is a United States copyright law that provides guidelines for online service provider liability in case of copyright infringement. Click here for more information about the DMCA, and see http://www.google.com/dmca.html for the process that Google requires in order to make a DMCA complaint.
> 
> Google may reinstate your app on Google Play upon receipt of a counter notification pursuant to sections 512(g)(2) and (3) of the DMCA. Click here for more information about the requirements of a counter notification and a link to a sample counter notification. If you have legal questions about this notification, you should retain your own legal counsel.
> 
> Please note that we have included a text copy of the Infringement Notice we received for your reference.
> 
> The Google Play Team
> 
> Text copy of DMCA complaint:
> 
> companyname: Flipkart Internet Private Limited
> represented_copyright_holder: Flipkart Internet Private Limited
> contact_email_noprefill: arup.saxena@flipkart.com
> login_email: arup.saxena@flipkart.com
> description_of_copyrighted_work: Our work is a shopping website called
> Flipkart located online at flipkart.com is engaged in the business of
> online marketplace, providing platform/technology and/or other
> mechanism/services to facilitate transactions, electronic commerce, mobile
> commerce, by and between respective buyers and sellers, enable dealing in
> various multiple categories of goods including but not limited to movies,
> music, games, mobiles, cameras, computers, apparels, footwear, healthcare
> and personal products, home appliances and electronics, etc..
> 
> Such unauthorized use of our logo and iframing our website is a serious
> crime. This unauthorized reproduction of Flipkart Internet Pvt Ltd
> multiple copyrights may be viewed in-app by first downloading and
> installing the app, allowing apps to open flipkart.com website and loading
> it within this app.
> 
> We DID NOT give these apps permission to use our original copyrighted work,
> in part or in full, and we are requesting that they be removed immediately
> from Google Playstore.
> 
> location_of_copyrighted_work:
> https://play.google.com/store/apps/details?id=com.flipkart.android
> https://www.flipkart.com/
> url_box:
> https://play.google.com/store/apps/details?id=flipkart.amazon.flipkart.amazon.flipkart.amazon.flipkart.amazon.flipkart.amazon.flipkart.amazon.flipkart.amazon.flipkart.amazon
> url_box:
> https://play.google.com/store/apps/details?id=app.shopping.olx.quikr.flipkart.amazon.phonepe.phonepe.india.online.jio.jio.ol.quikr.flipkart.amazon
> url_box:
> https://play.google.com/store/apps/details?id=com.allinoneapp.onlineshoppingapps
> url_box: https://play.google.com/store/apps/details?id=com.mobile.recharge
> url_box: https://play.google.com/store/apps/details?id=com.allonlineshopping
> url_box:
> https://play.google.com/store/apps/details?id=com.india.allinone.onlineshopping
> url_box:
> https://play.google.com/store/apps/details?id=com.onlineshopping.allinonedeals
> url_box:
> https://play.google.com/store/apps/details?id=makeinindia.flipkart2gud
> url_box: https://play.google.com/store/apps/details?id=com.bin.onesft.mkart
> url_box:
> https://play.google.com/store/apps/details?id=com.allinoneonlineshopping.app
> url_box:
> https://play.google.com/store/apps/details?id=org.liteforflipkartindiashopping
> url_box:
> https://play.google.com/store/apps/details?id=shopclues.ajio.shopping.shopclues.ajio.shopping.shopclues.ajio.shopping.shopclues.ajio.shopping
> url_box:
> https://play.google.com/store/apps/details?id=com.online.shopping.apps.india.recharge.offers
> url_box:
> https://play.google.com/store/apps/details?id=com.searchingwhat.rechargeandpay
> url_box:
> https://play.google.com/store/apps/details?id=com.kidstore.onlineshopping
> url_box:
> https://play.google.com/store/apps/details?id=allinoneshopping.amtech.com.allinoneshopping
> url_box:
> https://play.google.com/store/apps/details?id=com.shvahlabs.allonlinestores

As you can probably clearly tell by yourself, this has absolutely nothing to do with my app, heck, my app isn't even listed in the list of apps Flipkart asked to remove. 
It seems like a very unfortunate error that caused my app, which at the time of removal had over 7.5 Million downloads and a rating higher than 4.3 starts on to be removed from the Play Store. 

I obviously tried to contact Google, I sent a message via the Google Play Developer Console and explained the situation in detail. After reviewing my case I was told that the issue will be escalated to the Policy team. 4 days later I received the following generic (and most likely auto generated by a bot) response:

> Hi developer,
> 
> Thanks for contacting Google Play Developer Support.
> 
> We've reviewed your appeal but we're still unable to reinstate your app.
> 
> If you'd like to contest the removal of this app, please follow the instructions shared in the initial removal email and fill out the DMCA counter-notice form.
> 
> If your account is still in good standing and the nature of your app allows for republishing, you may consider distributing a new, non-copyright infringing version of your app to Google Play. As app names are unique, you'll need to use a slightly modified app name and a new package name when you upload the APK.
> 
> We are unable to comment further on the specific basis for this removal or provide guidance on bringing future versions of your app into policy compliance. Instead, please reference the reason for removal in the initial notification email from Google Play.
> 
> Regards,
> Jay
> The Google Play Team

The thing is, my app doesn't violate any copyrighted work or any intellectual property, I can't even dispute or submit a counter DMCA notice since I NEVER RECEIVED AN ACTUAL DMCA NOTICE AGAINST MY APP IN THE FIRST PLACE.

**Edit: I sent a counter DMCA notice as some people recommended, although technically no DMCA notice was issued against my app and although my app didn't violate any IP. Hopefully that would help.**

I'm at a loss in this situation, I feel powerless and abandoned by a platform I felt I could trust. 
I'm writing this in hope that someone with more knowledge in the subject than me or someone with better connections with actual human beings in the relevant departments in Google could help.

### [Reddit](https://www.reddit.com/r/Android/comments/4nimzg/app_i_created_an_always_on_app_for_amoled/)

Thank you,
Tomer

***Edit: I sent a counter DMCA notice as some people recommended, although technically no DMCA notice was issued against my app and although my app didn't violate any IP. Hopefully that would help.
The following is the message I sent to Google as the DMCA counter notice:***

> 
> On October 11th my app Always On AMOLED was removed from the Play Store, seemingly due to an error in the DMCA system.
> 
> It seems like a company named "Flipkart" issued a DMCA notice against several replicas of their app and somehow my app was mixed in the situation and removed from Google Play Store.
> 
> Upon reviewing the DMCA notice, it was evident that there was a mistake, my app isn't even listed in the list of apps Flipkart asked to remove nor was it mentioned in any way in the original notice.
> 
> My app doesn't violate any intellectual properties, I created all the assets in my app myself or used assets that were legally available for commercial use. My app never did anything that was remotely related to "Flipkart", I wasn't even aware to the existent of this company/app until I received the DMCA notice.
> 
> This situation is very unfortunate and I hope you could fix this issue and reinstate my app as soon as possible.
> 
> Regards,
> Tomer

**Comment by 0megaD** [comment]
They talk about filling some kind of DMCA counter form. You claim you cannot fill in the counter form, but what about this part from your e-mail?

> Click here for more information about the requirements of a counter notification and a link to a sample counter notification. If you have legal questions about this notification, you should retain your own legal counsel.

If you click those two links, are you missing any required information to be able to fill in the sample?

Here's another example for google's product: https://support.google.com/legal/contact/lr_counternotice?product=googleplus&uraw=&hl=en

Basically you'll say that some content of yours is gone, and that it should not be gone because you're the rightful owner, and then google should pick it up with that company. As you've not been involved in that company's takedown notice, they should be able to say "he's not one of them" and then your app will be reinstated.

**Comment by GregoryIwanek** [comment]
@0megaD I hope it would be that easy...
Unrelated to this specific case, but I'll share link to Reddit post from couple days ago when reddit cringe about google play store shi**ing on indie developers got to the tipping point.
https://www.reddit.com/r/androiddev/comments/9n88wv/the_future_of_android_development/

But I agree, you should make a case as visible as possible and try to reply to them. Somhow.

**Comment by rosenpin** [comment]
### The App Was Reinstated!
I want to thank everyone who helped getting this to Google's attention, and especially Ryne Hager from Android Police.
Thank you all for sharing supporting and providing meaningful help throughout this situation, this couldn't have been done without you!! :)

**Comment by bemnet4u** [comment]
I am in the same situation with google. I appreciate a retweet over here https://twitter.com/bemnet4u/status/1166594576594931713?s=21
