### ISSUE TITLE
Missing layout in repository causing build to fail

### ISSUE THREAD

**Issue by zygh0st** [rosenpin/AlwaysOnDisplayAmoled#249]
@rosenpin I think you might have forgotten to add `activity_main2.xml` to the repository as it's referenced by the `ClockPicker` class but doesn't exist anywhere.

**Comment by rosenpin** [comment]
There is no ColorPicker class in the project itself, the ColorPicker class is borrowed from the material-dialogs library:
`compile 'com.afollestad.material-dialogs:commons:0.8.6.0'`

I'm not sure what you are talking about but I assume the activity_main2.xml is located inside the material-dialogs library.

**Comment by rosenpin** [comment]
Sorry, I misspoke.
Yeah, you are correct.
I didn't add the xml layout of this activity because it's not ready at all.
Thanks for pointing that out, I'll remove the class now.

**Comment by rosenpin** [comment]
Fixed in 639959c46c02fccf6821611cda15296ca80a82b3
