### ISSUE TITLE
Views shouldn't be cached, especially as array isn't used

### ISSUE THREAD

**Issue by Maxr1998** [rosenpin/AlwaysOnDisplayAmoled#28]
[Here](https://github.com/rosenpin/AlwaysOnDisplayAmoled/blob/master/app/src/main/java/com/tomer/alwayson/Services/MainService.java#L191), you're caching your views, which could cause a memory leak, although you don't even use the cache (and don't have to, since the resource heavy things (the drawables) are cached anyway).

**Comment by rosenpin** [comment]
You're absolutely right
