### ISSUE TITLE
Feature: Turn off when main button is clicked

### ISSUE THREAD

**Issue by davidhedlund** [rosenpin/AlwaysOnDisplayAmoled#283]
There are no option to turn off the app when the main hardware button (the big button placed under most smartphone screens) is clicked on. Some new users are confused how to turn deactivate Always On AMOLED when it is active.

**Comment by rosenpin** [comment]
There is already an open issue regarding this:
https://github.com/rosenpin/AlwaysOnDisplayAmoled/issues/12

**Comment by davidhedlund** [comment]
@rosenpin Thank you for pointing that out.
