### ISSUE TITLE
Separated night and day screen brightness

### ISSUE THREAD

**Issue by Maxr1998** [rosenpin/AlwaysOnDisplayAmoled#29]
Night brightness could get enabled after sun went down and proximity sensor is returning a low ambient brightness

**Comment by rosenpin** [comment]
Shouldn't #b102e01 be enough?

**Comment by Maxr1998** [comment]
Yep, it is.
I didn't incorporate the time, but I guess it isn't that important.
Sensor alone is totally enough.
