### ISSUE TITLE
Brightness isn't being set back to original 100% of the time

### ISSUE THREAD

**Issue by rosenpin** [rosenpin/AlwaysOnDisplayAmoled#49]
As reported by Joseph Fountain in the Google Plus community

> I am not sure what triggers it, but the screen brightness change seems to stick sometimes when you open the phone, I have the brightness set to zero, and sometimes when I unlock the system brightness stays at zero, not sure if this is intentional﻿

**Comment by Maxr1998** [comment]
I experienced this as well, it happens when the Service crashes (it was a NPE for the wakelock) without calling onDestroy properly. Should be fixed now.

**Comment by rosenpin** [comment]
Great, thanks
