### ISSUE TITLE
[FEATURE REQUEST] sony xperia clock style/formatting

### ISSUE THREAD

**Issue by wilson289296** [rosenpin/AlwaysOnDisplayAmoled#565]
Forgive me if I'm being presumptuous, but it seems that something like this:

https://www.google.com/search?q=xperia+x+lockscreen+app&biw=1278&bih=962&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjuuZis3oTPAhVP5mMKHXOJCFc4ChD8BQgJKAQ#imgrc=dJR0vYFo-Nt4mM%3A

would be pretty simple to implement, and would look great on AOD. Thanks for taking the time!

**Comment by rosenpin** [comment]
Identical to the new S8 style digital clock
