### ISSUE TITLE
Watchface pops up when pressing power button twice to open camera on Nexus devices

### ISSUE THREAD

**Issue by pongo1231** [rosenpin/AlwaysOnDisplayAmoled#61]
The Always on Screen gets activated when pressing the power button twice, which is the shortcut to open the camera on Nexus devices (tested on my 6P).

The camera starts up and the phone vibrates as usual, but the watchface pops up and blocks the screen. The user has to press the power button twice again to make the camera app appear.

**Comment by rosenpin** [comment]
Fixed in version 0.67
