### ISSUE TITLE
[0.9.5b25] Media controls incorrectly persistent + volume button toggle issues

### ISSUE THREAD

**Issue by wilson289296** [rosenpin/AlwaysOnDisplayAmoled#614]
Media controls are persistent on AOD even when no notifications containing media controls are present/nothing is playing. Tried killing and restarting service but controls continued to be visible. Issue is not always present, seems to be randomly occurring.
Also, "disable volume button" toggle does not function, volume buttons are disabled AOD regardless of toogle position. 
Rooted S6 Edge+, stock 6.0
- [ ] Persistent music controls
- [x] Volume buttons are disabled regardless of the settings

**Comment by rosenpin** [comment]
Thanks for reporting.

**Comment by rosenpin** [comment]
Music controls should now be visible as long as the music notification is displayed
