### ISSUE TITLE
Non-free software (Greenify) recommended

### ISSUE THREAD

**Issue by davidhedlund** [rosenpin/AlwaysOnDisplayAmoled#625]
Greenify is [non-free](https://gitlab.com/fdroid/fdroiddata/issues/502#note_15429224). Can you please the recommendation (text and link) from Always On AMOLED?

**Comment by rosenpin** [comment]
I commented in gitlab issue

> Always On AMOLED Plugin is open source
> https://github.com/rosenpin/AlwaysOnAmoledPlugin
> The Greenify requirement is already removed in the latest beta

**Comment by davidhedlund** [comment]
@rosenpin
>The Greenify requirement is already removed in the latest beta
That is good news.

**Comment by davidhedlund** [comment]
I'll let this issue be open until it have been removed in the stable f-droid release. Is that ok?

**Comment by rosenpin** [comment]
I'm keeping the Greenify integration in the app, I will just remove the red text and warning if Greenify is not installed.
You can keep the issue open if you feel like it

**Comment by davidhedlund** [comment]
>I'm keeping the Greenify integration in the app

What does that mean?

**Comment by rosenpin** [comment]
It means that users will still be able take advantage of Greenify if it is installed.
My app however will not recommend it.

**Comment by davidhedlund** [comment]
Ok, please just mention this in the documentation (and that Greenify is non-free).

**Comment by davidhedlund** [comment]
There are other options, I have not checked license of Doze yet.

**Comment by davidhedlund** [comment]
Thank you for making a great software @rosenpin. I love it.
