### ISSUE TITLE
Bugs in settings

### ISSUE THREAD

**Issue by jdrescher2006** [rosenpin/AlwaysOnDisplayAmoled#69]
First: There is a bug in settings when choosing the font. There font descriptions are missing. I am on german language.
[screenshot_2016-07-06-14-21-55](https://cloud.githubusercontent.com/assets/12234756/16617728/a5412aac-4385-11e6-9fea-486dba8adacf.png)
Second: the text color chooser is always set to  white color when the dialog is opened.

**Comment by rosenpin** [comment]
Yeah, it seems like a Samsung only issue.
I fixed it in the latest update, you should get it later today.
Once you do, let me know if it works.

**Comment by jdrescher2006** [comment]
No Problem, I will check this out.

Am 6. Juli 2016 14:47:32 MESZ, schrieb Tomer Rosenfeld <notifications@github.com>:
>Yeah, it seems like a Samsung only issue.
>I fixed it in the latest update, you should get it later today.
>Once you do, let me know if it works.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rosenpin/AlwaysOnDisplayAmoled/issues/69#issuecomment-230761020

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
