### ISSUE TITLE
Full Stop

### ISSUE THREAD

**Issue by IlicMiljan** [rosenpin/AlwaysOnDisplayAmoled#786]
When Always On Screen is turned on it shows clock with full stop instead colon. Example:
9.30 instead 9:30

**Comment by rosenpin** [comment]
Please provide a screenshot

**Comment by MintNet** [comment]
http://www.upslike.net/image/9A8Ob

**Comment by rosenpin** [comment]
Thanks.
The digital clock uses the system preferences for the time, which local do you have chosen in your device settings?
