### ISSUE TITLE
Service stops when app is not running in background

### ISSUE THREAD

**Issue by rosenpin** [rosenpin/AlwaysOnDisplayAmoled#9]
Users reported that the service stops working after clearing the app from recents or not opening it.

**Comment by Maxr1998** [comment]
The only way to resolve this is to enable the Notification. The user can block notifications from this app to hide the notification while retaining functionality, but only on API23 and above. A dialog with this information seems like a good idea.

**Comment by rosenpin** [comment]
Right, I'll just make the 'Show persistent notification' a default and show a dialog when the user tries to disable it.
Thanks!
