### ISSUE TITLE
Aod goes to turning on display n lockscreen after 13 sec

### ISSUE THREAD

**Issue by pratz07** [rosenpin/AlwaysOnDisplayAmoled#901]
Are you working on a fix??? I love this app but not able to use it bought a pro too.

Always On Display disappears after about 15 seconds on HUAWEI devices

**Comment by rosenpin** [comment]
It will be fixed once I can get my hands on a HUAWEI device.
I currently have no HUAWEI device to test it on.
I will leave this issue open for now as I couldn't find a related open issue
