### ISSUE TITLE
Notifications not shown

### ISSUE THREAD

**Issue by RIPT1DE** [rosenpin/AlwaysOnDisplayAmoled#958]
When I receive a notification, I can hear the notification sound but it dosent show up on the screen

**Comment by rosenpin** [comment]
Do you have a Samsung device?
If so, this is a known issue and there is already an open issue regarding this bug.

**Comment by RIPT1DE** [comment]
Thank you for clearing that up. 
I'm kind of a developer myself and would like to help you with it.

**Comment by rosenpin** [comment]
I'm not sure there's a better way to implement it than the one I'm currently using, I'll investigate this issue further once other, more major bugs are fixed.
