### ISSUE TITLE
Screen off memo

### ISSUE THREAD

**Issue by a2597** [rosenpin/AlwaysOnDisplayAmoled#998]
On Note 5, the screen off memo doesn't work while AOD is on.
(I believe it is hiding behind the AOD, as I still get the vibration from pulling out the SPen)
If it is set to a timer and has already turned off, the screen off memo works.

Two fixes come to mind:
Easy method: Allow a shortcut to turn OFF the AOD, bypassing timers and overriding the always on (this could benefit all users)
Potentially harder: Look for the SPen Detach event and turn off the AOD.

**Comment by rosenpin** [comment]
This is a known issue #144

Thanks for the feedback though, I will try to solve it in the next update.
